# Generated by Django 6.0 on 2025-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
